
version: '3.8'
services:
  web:
    container_name: 'web'
    user: $DOCKER_UID:$DOCKER_GID
    build:
      context: .
      args:
        UID: $DOCKER_UID
        GID: $DOCKER_GID
        UNAME: $USER
    tty: true
    working_dir: '/home/$USER/workspace'
    volumes:
      - .:/home/$USER/workspace:cached
    entrypoint: /bin/bash
    ports: 
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gongbu
      - SPRING_DATASOURCE_USERNAME=gongbu_admin
      - SPRING_DATASOURCE_PASSWORD=1234

  db:
    image: postgres:11.14
    container_name: db
    environment:
      - POSTGRES_DB=gongbu
      - POSTGRES_USER=gongbu_admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
    volumes:
      - gongbu-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    #restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: gongbu@db.info
      PGADMIN_DEFAULT_PASSWORD: gongbu
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  gongbu-data:
  pgadmin: