version: 0.2

phases:
  install:
    # https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/Dockerfile
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - python ./server/create_application_props.py

      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})

      # docker pull limit対策
      - ECR_GRADLE_URI=$WEB_REPOSITORY_URL:gradle-7.2.0-jdk16-openj9
      - DOCKER_GRADLE_URI=gradle:7.2.0-jdk16-openj9
      - docker pull $ECR_GRADLE_URI || (docker pull $DOCKER_GRADLE_URI && docker tag $DOCKER_GRADLE_URI $ECR_GRADLE_URI && docker push $ECR_GRADLE_URI && true)

  build:
    commands:
      - ECR_WEB_URI=$WEB_REPOSITORY_URL:latest
      - docker build -t $ECR_WEB_URI --build-arg ECR_GRADLE_URI=$ECR_GRADLE_URI .
      - docker push $ECR_WEB_URI

  post_build:
    commands:
      - export EDITED_TASK_DEF=task_definition.json
      - export LAST_TASK_DEF_ARN=$(aws ecs list-task-definitions --family-prefix $ECS_FAMILY --sort DESC --max-items 1 --query 'taskDefinitionArns[0]' --output json)

      # LAST_TASK_DEF_ARNの結果値が「"」で囲まれていて困る。取り除く
      - LAST_TASK_DEF_ARN="${LAST_TASK_DEF_ARN%\"}"
      - LAST_TASK_DEF_ARN="${LAST_TASK_DEF_ARN#\"}"
      - echo $LAST_TASK_DEF_ARN
      - aws ecs describe-task-definition --task-definition $LAST_TASK_DEF_ARN --output json | jq . > origin_task_definition.json
      - python ./server/edit_task_def.py

      - cat server/appspec.yaml | sed -e s@\<SB_CONTAINER_NAME\>@$SB_CONTAINER_NAME@ > appspec.yaml

      - cat $EDITED_TASK_DEF
      - cat appspec.yaml

artifacts:
  files:
    - appspec.yaml
    - task_definition.json