version: 0.2

phases:
  install:
    # https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/Dockerfile
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - cd ./server && javac CreateSpringBootProps.java && java CreateSpringBootProps

      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})

      - docker images
      # docker pull limit対策
      - ECR_GRADLE_URI=$WEB_REPOSITORY_URL:gradle-7.2.0-jdk16-openj9
      - DOCKER_GRADLE_URI=gradle:7.2.0-jdk16-openj9
      - docker pull $ECR_GRADLE_URI || (docker pull $DOCKER_GRADLE_URI && docker tag $DOCKER_GRADLE_URI $ECR_GRADLE_URI && docker push $ECR_GRADLE_URI && true)
      - docker images