name: Test for CI, S3 cp for CD

on: [push]

jobs:
  test:

    runs-on: ubuntu-20.04
    env:
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      LINE_CLIENT_SECRET: ${{ secrets.LINE_CLIENT_SECRET }}
      LINE_CLIENT_ID: ${{ secrets.LINE_CLIENT_ID }}
      DOCKER_IMAGES_FOR_CI_CACHE_PATH: docker-images
    steps:
    - uses: actions/checkout@v2

    - name: Cache Docker images for CI
      id: cache-docker-images
      uses: actions/cache@v2
      with:
        path: ${{ env.DOCKER_IMAGES_FOR_CI_CACHE_PATH }}
        key: ${{ runner.os }}-github-actions

    - name: Pull and save Docker images for CI
      if: steps.cache-docker-images.outputs.cache-hit != 'true'
      run: |
        docker-compose -f docker-compose-gitaction.yml build
        docker images --format '{{.Repository}}:{{.Tag}}'
        docker save $(docker images --format '{{.Repository}}:{{.Tag}}') -o ${DOCKER_IMAGES_FOR_CI_CACHE_PATH}

    - run: docker load -i ${DOCKER_IMAGES_FOR_CI_CACHE_PATH}
    - run: docker-compose -f docker-compose-gitaction.yml up --abort-on-container-exit

  s3_cp_for_aws_codepipeline:
    needs: test
    if: github.ref == 'refs/heads/production'

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - run: git archive -o build.zip HEAD
    - run: aws s3 cp ./build.zip s3://gongbu-app-pipeline-src/build.zip