name: Test for CI, S3 cp for CD

on: [push]

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        spring.security.oauth2.client.registration.google.client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        spring.security.oauth2.client.registration.google.client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        spring.security.oauth2.client.registration.line.client-secret: ${{ secrets.LINE_CLIENT_SECRET }}
        spring.security.oauth2.client.registration.line.client-secret: ${{ secrets.LINE_CLIENT_ID }}
    - run: docker-compose -f docker-compose-gitaction.yml build
    - run: docker-compose -f docker-compose-gitaction.yml up --abort-on-container-exit

  s3_cp_for_aws_codepipeline:
    needs: test
    if: github.ref == 'refs/heads/production'

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - run: git archive -o build.zip HEAD
    - run: aws s3 cp ./build.zip s3://gongbu-app-pipeline-src/build.zip